# Generated by Django 4.1.1 on 2024-02-11 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MuhasebeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onayno', models.CharField(max_length=100)),
                ('onayaciklama', models.CharField(default='my_default_value', max_length=100)),
                ('onaytar', models.CharField(max_length=12)),
                ('onay_odemetutar', models.CharField(max_length=20)),
                ('onay_parabirimi', models.CharField(max_length=20)),
                ('onay_odemeyolu', models.CharField(max_length=20)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
