# Generated by Django 4.1.1 on 2024-02-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnayBelgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='belgeler/')),
                ('yukleme_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
