# Generated by Django 4.1.1 on 2024-02-05 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muhasebeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muhasebemodel',
            name='nickname',
        ),
        migrations.AddField(
            model_name='muhasebemodel',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
